version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - "5672:5672"   # Porta para comunicação com aplicações (AMQP)
      - "8080:15672"  # Porta para acessar a interface de administração web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
